In [1]:
import pandas as pd
import matplotlib as plt
import gmaps
import csv
import numpy as np

In [25]:
from config import g_key2

In [26]:
gmaps.configure(api_key=g_key2)

In [4]:
file_to_load = pd.read_csv('Data\WeatherPy_vacation.csv')
file_to_load

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Rain inches(Past 3hrs),Snow inches(Past 3hrs)
0,Shingu,JP,2020-04-06 02:35:54,33.73,135.98,57.20,40,20,14.99,0.00,0.00
1,Rikitea,PF,2020-04-06 02:35:54,-23.12,-134.97,75.45,66,0,10.40,0.00,0.00
2,Surt,LY,2020-04-06 02:35:54,31.21,16.59,56.34,68,7,5.06,0.00,0.00
3,Teguldet,RU,2020-04-06 02:35:54,57.31,88.17,37.81,72,0,10.16,0.00,0.00
4,Nobres,BR,2020-04-06 02:35:41,-14.72,-56.33,77.49,82,100,1.28,0.33,0.00
...,...,...,...,...,...,...,...,...,...,...,...
572,Alihe,CN,2020-04-06 02:36:49,50.57,123.72,37.35,49,0,13.09,0.00,0.00
573,Powell,US,2020-04-06 02:36:49,40.16,-83.08,48.20,81,1,6.93,0.00,0.00
574,San Antonio,US,2020-04-06 02:36:50,29.42,-98.49,68.00,82,90,4.70,0.00,0.00
575,Morgan City,US,2020-04-06 02:36:50,29.70,-91.21,70.00,73,1,4.70,0.00,0.00
576,Chumikan,RU,2020-04-06 02:36:50,54.72,135.31,31.91,97,100,3.98,0.00,1.04

In [5]:
file_to_load.loc[(file_to_load["Country"] == "SA")].head(10)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Rain inches(Past 3hrs),Snow inches(Past 3hrs)
33,Najran,SA,2020-04-06 02:35:57,17.49,44.13,71.60,37,5,3.85,0.0,0.0
192,Umm Lajj,SA,2020-04-06 02:36:13,25.02,37.27,80.04,42,0,3.89,0.0,0.0
307,Abha,SA,2020-04-06 02:36:23,18.22,42.51,60.80,67,0,4.52,0.0,0.0
492,Buraydah,SA,2020-04-06 02:32:45,26.33,43.98,69.80,88,20,3.36,0.0,0.0
540,Sakakah,SA,2020-04-06 02:36:47,29.97,40.21,71.60,24,52,5.82,0.0,0.0

In [27]:
# Latitude-longitude pairs
najran = (17.49, 44.13)
umm_lajj = (25.02, 37.27)
abha = (18.22, 42.51)
buraydah = (26.33, 43.98)
pref_hotels = [najran, umm_lajj, abha, buraydah]

fig = gmaps.figure()
najran2umm_lajj = gmaps.directions_layer(najran, umm_lajj, waypoints=[abha, buraydah])

fig.add_layer(najran2umm_lajj)
#fig.add_layer(umm_lajj2abha)
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
countries_df = pd.DataFrame(file_to_load["Country"])
countries_df
for i in countries_df:
    countries_df = countries_df.append({'A': i}, ignore_index=True)

In [28]:
# Add spots and a pop-up marker for each city.
locations = pref_hotels
gmaps.configure(api_key=g_key)
fig = gmaps.figure(center=umm_lajj, zoom_level= 5)
marker_layer = gmaps.marker_layer(locations)

fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [29]:
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

In [30]:
# Store the DataFrame Row.
pref_hotels_df = pd.DataFrame(pref_hotels)
pref_hotels_df
hotel_info = [info_box_template.format(**row) for index, row in file_to_load.iterrows()]

In [31]:
locations = pref_hotels

fig = gmaps.figure(center=abha, zoom_level=4)

fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))