In [1]:
import pandas as pd
import matplotlib as plt
import gmaps
import csv
import numpy as np

In [9]:
from config import g_key2

In [10]:
gmaps.configure(api_key=g_key2)

In [3]:
file_to_load = pd.read_csv('Data\WeatherPy_vacation.csv')
file_to_load

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Rain inches(Past 3hrs),Snow inches(Past 3hrs)
0,Shingu,JP,2020-04-06 02:35:54,33.73,135.98,57.20,40,20,14.99,0.00,0.00
1,Rikitea,PF,2020-04-06 02:35:54,-23.12,-134.97,75.45,66,0,10.40,0.00,0.00
2,Surt,LY,2020-04-06 02:35:54,31.21,16.59,56.34,68,7,5.06,0.00,0.00
3,Teguldet,RU,2020-04-06 02:35:54,57.31,88.17,37.81,72,0,10.16,0.00,0.00
4,Nobres,BR,2020-04-06 02:35:41,-14.72,-56.33,77.49,82,100,1.28,0.33,0.00
...,...,...,...,...,...,...,...,...,...,...,...
572,Alihe,CN,2020-04-06 02:36:49,50.57,123.72,37.35,49,0,13.09,0.00,0.00
573,Powell,US,2020-04-06 02:36:49,40.16,-83.08,48.20,81,1,6.93,0.00,0.00
574,San Antonio,US,2020-04-06 02:36:50,29.42,-98.49,68.00,82,90,4.70,0.00,0.00
575,Morgan City,US,2020-04-06 02:36:50,29.70,-91.21,70.00,73,1,4.70,0.00,0.00
576,Chumikan,RU,2020-04-06 02:36:50,54.72,135.31,31.91,97,100,3.98,0.00,1.04

In [4]:
file_to_load.loc[(file_to_load["Country"] == "RU")].head()

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Rain inches(Past 3hrs),Snow inches(Past 3hrs)
3,Teguldet,RU,2020-04-06 02:35:54,57.31,88.17,37.81,72,0,10.16,0.0,0.00
8,Khatanga,RU,2020-04-06 02:32:32,71.97,102.50,27.57,97,100,12.26,0.0,0.12
17,Leningradskiy,RU,2020-04-06 02:35:55,69.38,178.42,1.08,88,100,15.03,0.0,0.00
31,Talnakh,RU,2020-04-06 02:35:56,69.49,88.40,32.00,96,75,22.37,0.0,0.00
36,Pevek,RU,2020-04-06 02:35:57,69.70,170.31,-2.88,91,49,9.66,0.0,0.00

In [7]:
# Latitude-longitude pairs
Teguldet = (57.31, 88.17)
Khatanga = (71.97, 102.50)
Leningradskiy = (69.70, 178.42)
Pevek = (69.70, 170.31)

fig = gmaps.figure()
Teguldet2Khatanga = gmaps.directions_layer(Teguldet, Khatanga)
fig.add_layer(Teguldet2Khatanga)
fig

Figure(layout=FigureLayout(height='420px'))